### ISSUE TITLE
library.properties encoding (ANSI) breaks arduino IDE 2.0 library manager

### ISSUE THREAD

**Issue by Jones1403** [VincentLim/TimerFive#6]
Hello,

I've experienced an issue with this library. Using this library on the new arduino IDE 2.0 breaks the library manager of the IDE.
The apparent reason is that the current version of IDE 2.0 only supports UTF-8 encoding of the library.properties file.

in the current version of this library, the encoding of that file is ANSI.

changing it to UTF-8 using e.g. Notepad++ resolves the issue.
The issue was logged on the arduino forum and quickly resolved:
https://forum.arduino.cc/t/timerfive-library-breaks-library-manager-of-ardiuno-ide-2-0/859764/3

**Comment by VincentLim** [comment]
Hello, 

Thanks for the feedback, I'll try to get some time soon to reencode files

**Comment by VincentLim** [comment]
Blindly fixed (no test with Arduino IDE)
Please reopen if needed
